### ISSUE TITLE
Your lovely mod breaks my world and report to another mod's issue😅

### ISSUE THREAD

**Issue by KELETU66666** [MennoMax/astikor-carts#100]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 8/6/24 4:46 PM
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:81)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1464)
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:167)
	at com.github.alexthe666.iceandfire.entity.EntityBlackFrostDragon.func_70636_d(EntityBlackFrostDragon.java:61)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1430)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:81)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1464)
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:167)
	at com.github.alexthe666.iceandfire.entity.EntityBlackFrostDragon.func_70636_d(EntityBlackFrostDragon.java:61)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1430)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:blackfrost (com.github.alexthe666.iceandfire.entity.EntityBlackFrostDragon)
	Entity ID: 3613
	Entity Name: entity.blackfrost.name
	Entity's Exact location: 43.34, 64.00, 265.69
	Entity's Block location: World: (43,64,265), Chunk: (at 11,4,9 in 2,16; contains blocks 32,0,256 to 47,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.19
	Entity's Passengers: [EntityDreadQueen['Dread Queen'/3611, l='New World', x=43.33, y=72.19, z=271.29]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['keletu'/2465, l='New World', x=50.47, y=73.00, z=245.95]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: 6305831112027656090
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (48,64,256), Chunk: (at 0,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 275 game time, 275 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 125381 (now: false), thunder time: 110079 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_332, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 543092144 bytes (517 MB) / 1427111936 bytes (1361 MB) up to 7549222912 bytes (7199 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1136m -Xmx7577m
	IntCache: cache: 4, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version        | Source                          | Signature                                |
	|:------ |:------------ |:-------------- |:------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft    | 1.12.2         | minecraft.jar                   | None                                     |
	| LCHIJA | mcp          | 9.42           | minecraft.jar                   | None                                     |
	| LCHIJA | FML          | 8.0.99.99      | forge-1.12.2-14.23.5.2860.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge        | 14.23.5.2860   | forge-1.12.2-14.23.5.2860.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | astikorcarts | 1.12.2-0.1.2.8 | astikorcarts-1.12.2-0.1.2.8.jar | None                                     |
	| LCHIJA | llibrary     | 1.7.20         | llibrary-1.7.20-1.12.2.jar      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire   | 1.9.1-1.3.0    | Ice and Fire-2.0.0.jar          | None                                     |
	| LCHIJA | jei          | 4.16.1.1012    | jei_1.12.2-4.16.1.1012.jar      | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['keletu'/2465, l='New World', x=50.47, y=73.00, z=245.95]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by KELETU66666** [comment]
btw, i spend 4 hour to find that😅, "thank" you
