### ISSUE TITLE
Cannot open Plow inventory on Server

### ISSUE THREAD

**Issue by Aronnaxx** [MennoMax/astikor-carts#65]
Here is the Server Log for the problem

[03Mar2021 22:10:33.844] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
--
2829 | java.util.NoSuchElementException: Registry object not present: astikorcarts:plow
2830 | at de.mennomax.astikorcarts.util.RegObject.get(RegObject.java:25) ~[astikorcarts:1.1.1]
2831 | at de.mennomax.astikorcarts.inventory.container.PlowContainer.<init>(PlowContainer.java:18) ~[astikorcarts:1.1.1]
2832 | at de.mennomax.astikorcarts.entity.PlowEntity.lambda$openContainer$0(PlowEntity.java:170) ~[astikorcarts:1.1.1]
2833 | at net.minecraft.inventory.container.SimpleNamedContainerProvider.createMenu(SourceFile:25) ~[?:?]
2834 | at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:222) ~[forge:?]
2835 | at de.mennomax.astikorcarts.entity.PlowEntity.openContainer(PlowEntity.java:169) ~[astikorcarts:1.1.1]
2836 | at de.mennomax.astikorcarts.entity.PlowEntity.func_184230_a(PlowEntity.java:116) ~[astikorcarts:1.1.1]
2837 | at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:940) ~[?:?]
2838 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1194) ~[?:?]
2839 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74) ~[?:?]
2840 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?]
2841 | at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
2842 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
2843 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
2844 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
2845 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
2846 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
2847 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
2848 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
2849 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
2850 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
2851 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
2852 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
2853 | at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
2854 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by pau101** [comment]
Thanks for reporting!

The plow works fine for me, what other mods do you have installed?

**Comment by Aronnaxx** [comment]
abnormals_core-1.16.4-3.0.6.jar

alexsmobs-1.6.0.jar

anviltweaks-3.1.jar

astikorcarts-1.16.5-1.1.1.jar

AutoRegLib-1.6-47.jar

BetterMineshafts-Forge-1.16.4-2.0.1.jar

cgm-1.0.1-1.16.3.jar

citadel-1.6.1.jar

create-mc1.16.3_v0.3e.jar

DoggyTalents-1.16.4-2.0.1.3.jar

endergetic-1.16.4-3.0.0.jar

extraboats-1.16.5-2.1.0.jar

goblintraders-1.2.2-1.16.3.jar

Hwyla-forge-1.10.11-B78_1.16.2.jar

iceandfire-2.1.6-1.16.4.jar

jei-1.16.4-7.6.1.71.jar

Mekanism-1.16.5-10.0.21.448.jar

MekanismAdditions-1.16.5-10.0.21.448.jar

MekanismGenerators-1.16.5-10.0.21.448.jar

MekanismTools-1.16.5-10.0.21.448.jar

obfuscate-0.6.0-1.16.3.jar

Quark-r2.4-308.jar

QuarkOddities-1.16.3.jar

savageandravage-1.16.4-3.0.0.jar

smallships-1.16.5-1.0.0.jar

The_Undergarden-1.16.5-0.4.5.jar

upgrade_aquatic-1.16.5-3.0.1.jar

valhelsia_structures-16.0.5.jar

YungsApi-1.16.4-Forge-4.jar
